package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1458</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class BalanceDiff extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int login() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public BalanceDiff login(int login) {
		this.io.setIntField(this, 0, login);
		return this;
	}
	@Field(1) 
	public double diff() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public BalanceDiff diff(double diff) {
		this.io.setDoubleField(this, 1, diff);
		return this;
	}
	public BalanceDiff() {
		super();
	}
	public BalanceDiff(Pointer pointer) {
		super(pointer);
	}
}
