package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.TimeT;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:823</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ChartInfo extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * symbol<br>
	 * C type : char[12]
	 */
	@Array({12}) 
	@Field(0) 
	public Pointer<Byte > symbol() {
		return this.io.getPointerField(this, 0);
	}
	/** period (PERIOD_*) */
	@Field(1) 
	public int period() {
		return this.io.getIntField(this, 1);
	}
	/** period (PERIOD_*) */
	@Field(1) 
	public ChartInfo period(int period) {
		this.io.setIntField(this, 1, period);
		return this;
	}
	/** start of chart block */
	@Field(2) 
	public TimeT start() {
		return this.io.getTimeTField(this, 2);
	}
	/** start of chart block */
	@Field(2) 
	public ChartInfo start(TimeT start) {
		this.io.setTimeTField(this, 2, start);
		return this;
	}
	/** end of chart block */
	@Field(3) 
	public TimeT end() {
		return this.io.getTimeTField(this, 3);
	}
	/** end of chart block */
	@Field(3) 
	public ChartInfo end(TimeT end) {
		this.io.setTimeTField(this, 3, end);
		return this;
	}
	/** timestamp of existing chart base */
	@Field(4) 
	public TimeT timesign() {
		return this.io.getTimeTField(this, 4);
	}
	/** timestamp of existing chart base */
	@Field(4) 
	public ChartInfo timesign(TimeT timesign) {
		this.io.setTimeTField(this, 4, timesign);
		return this;
	}
	/** request mode */
	@Field(5) 
	public int mode() {
		return this.io.getIntField(this, 5);
	}
	/** request mode */
	@Field(5) 
	public ChartInfo mode(int mode) {
		this.io.setIntField(this, 5, mode);
		return this;
	}
	public ChartInfo() {
		super();
	}
	public ChartInfo(Pointer pointer) {
		super(pointer);
	}
}
