package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:274</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ConGroupMargin extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * security<br>
	 * C type : char[12]
	 */
	@Array({12}) 
	@Field(0) 
	public Pointer<Byte > symbol() {
		return this.io.getPointerField(this, 0);
	}
	/** swap size for long and short positions */
	@Field(1) 
	public double swap_long() {
		return this.io.getDoubleField(this, 1);
	}
	/** swap size for long and short positions */
	@Field(1) 
	public ConGroupMargin swap_long(double swap_long) {
		this.io.setDoubleField(this, 1, swap_long);
		return this;
	}
	/** swap size for long and short positions */
	@Field(2) 
	public double swap_short() {
		return this.io.getDoubleField(this, 2);
	}
	/** swap size for long and short positions */
	@Field(2) 
	public ConGroupMargin swap_short(double swap_short) {
		this.io.setDoubleField(this, 2, swap_short);
		return this;
	}
	/** margin divider */
	@Field(3) 
	public double margin_divider() {
		return this.io.getDoubleField(this, 3);
	}
	/** margin divider */
	@Field(3) 
	public ConGroupMargin margin_divider(double margin_divider) {
		this.io.setDoubleField(this, 3, margin_divider);
		return this;
	}
	/** C type : int[7] */
	@Array({7}) 
	@Field(4) 
	public Pointer<Integer > reserved() {
		return this.io.getPointerField(this, 4);
	}
	public ConGroupMargin() {
		super();
	}
	public ConGroupMargin(Pointer pointer) {
		super(pointer);
	}
}
