package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:704</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ConGatewayRule extends StructObject {
	static {
		BridJ.register();
	}
	/** enable flag 0 - disabled, 1 - enabled */
	@Field(0) 
	public int enable() {
		return this.io.getIntField(this, 0);
	}
	/** enable flag 0 - disabled, 1 - enabled */
	@Field(0) 
	public ConGatewayRule enable(int enable) {
		this.io.setIntField(this, 0, enable);
		return this;
	}
	/**
	 * public name<br>
	 * C type : char[64]
	 */
	@Array({64}) 
	@Field(1) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * symbol\symbols mask\symbols group name<br>
	 * C type : char[128]
	 */
	@Array({128}) 
	@Field(2) 
	public Pointer<Byte > request_symbol() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * group name or group mask<br>
	 * C type : char[128]
	 */
	@Array({128}) 
	@Field(3) 
	public Pointer<Byte > request_group() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * reserved<br>
	 * C type : int[32]
	 */
	@Array({32}) 
	@Field(4) 
	public Pointer<Integer > request_reserved() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * account name<br>
	 * C type : char[64]
	 */
	@Array({64}) 
	@Field(5) 
	public Pointer<Byte > exe_account_name() {
		return this.io.getPointerField(this, 5);
	}
	/** account internal id */
	@Field(6) 
	public int exe_account_id() {
		return this.io.getIntField(this, 6);
	}
	/** account internal id */
	@Field(6) 
	public ConGatewayRule exe_account_id(int exe_account_id) {
		this.io.setIntField(this, 6, exe_account_id);
		return this;
	}
	/** max. devation */
	@Field(7) 
	public int exe_max_deviation() {
		return this.io.getIntField(this, 7);
	}
	/** max. devation */
	@Field(7) 
	public ConGatewayRule exe_max_deviation(int exe_max_deviation) {
		this.io.setIntField(this, 7, exe_max_deviation);
		return this;
	}
	/** max profit slippage in pips */
	@Field(8) 
	public int exe_max_profit_slippage() {
		return this.io.getIntField(this, 8);
	}
	/** max profit slippage in pips */
	@Field(8) 
	public ConGatewayRule exe_max_profit_slippage(int exe_max_profit_slippage) {
		this.io.setIntField(this, 8, exe_max_profit_slippage);
		return this;
	}
	/** max profit slippage volume in lots */
	@Field(9) 
	public int exe_max_profit_slippage_lots() {
		return this.io.getIntField(this, 9);
	}
	/** max profit slippage volume in lots */
	@Field(9) 
	public ConGatewayRule exe_max_profit_slippage_lots(int exe_max_profit_slippage_lots) {
		this.io.setIntField(this, 9, exe_max_profit_slippage_lots);
		return this;
	}
	/** max losing slippage in pips */
	@Field(10) 
	public int exe_max_losing_slippage() {
		return this.io.getIntField(this, 10);
	}
	/** max losing slippage in pips */
	@Field(10) 
	public ConGatewayRule exe_max_losing_slippage(int exe_max_losing_slippage) {
		this.io.setIntField(this, 10, exe_max_losing_slippage);
		return this;
	}
	/** max losing slippage volume in lots */
	@Field(11) 
	public int exe_max_losing_slippage_lots() {
		return this.io.getIntField(this, 11);
	}
	/** max losing slippage volume in lots */
	@Field(11) 
	public ConGatewayRule exe_max_losing_slippage_lots(int exe_max_losing_slippage_lots) {
		this.io.setIntField(this, 11, exe_max_losing_slippage_lots);
		return this;
	}
	/** account current position */
	@Field(12) 
	public int exe_account_pos() {
		return this.io.getIntField(this, 12);
	}
	/** account current position */
	@Field(12) 
	public ConGatewayRule exe_account_pos(int exe_account_pos) {
		this.io.setIntField(this, 12, exe_account_pos);
		return this;
	}
	/** coverage percentage */
	@Field(13) 
	public int exe_volume_percent() {
		return this.io.getIntField(this, 13);
	}
	/** coverage percentage */
	@Field(13) 
	public ConGatewayRule exe_volume_percent(int exe_volume_percent) {
		this.io.setIntField(this, 13, exe_volume_percent);
		return this;
	}
	/**
	 * reserved<br>
	 * C type : int[26]
	 */
	@Array({26}) 
	@Field(14) 
	public Pointer<Integer > exe_reserved() {
		return this.io.getPointerField(this, 14);
	}
	public ConGatewayRule() {
		super();
	}
	public ConGatewayRule(Pointer pointer) {
		super(pointer);
	}
}
