package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:438</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ConManagerSec extends StructObject {
	static {
		BridJ.register();
	}
	/** internal data */
	@Field(0) 
	public int internal() {
		return this.io.getIntField(this, 0);
	}
	/** internal data */
	@Field(0) 
	public ConManagerSec internal(int internal) {
		this.io.setIntField(this, 0, internal);
		return this;
	}
	/** enable */
	@Field(1) 
	public int enable() {
		return this.io.getIntField(this, 1);
	}
	/** enable */
	@Field(1) 
	public ConManagerSec enable(int enable) {
		this.io.setIntField(this, 1, enable);
		return this;
	}
	/** min. lots */
	@Field(2) 
	public int minimum_lots() {
		return this.io.getIntField(this, 2);
	}
	/** min. lots */
	@Field(2) 
	public ConManagerSec minimum_lots(int minimum_lots) {
		this.io.setIntField(this, 2, minimum_lots);
		return this;
	}
	/** max. lots */
	@Field(3) 
	public int maximum_lots() {
		return this.io.getIntField(this, 3);
	}
	/** max. lots */
	@Field(3) 
	public ConManagerSec maximum_lots(int maximum_lots) {
		this.io.setIntField(this, 3, maximum_lots);
		return this;
	}
	/**
	 * reserved<br>
	 * C type : int[16]
	 */
	@Array({16}) 
	@Field(4) 
	public Pointer<Integer > unused() {
		return this.io.getPointerField(this, 4);
	}
	public ConManagerSec() {
		super();
	}
	public ConManagerSec(Pointer pointer) {
		super(pointer);
	}
}
