package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * ---<br>
 * <i>native declaration : MT4ManagerAPI.h:499</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ConSessions extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * quote sessions<br>
	 * C type : ConSession[3]
	 */
	@Array({3}) 
	@Field(0) 
	public Pointer<ConSession > quote() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * trade sessions<br>
	 * C type : ConSession[3]
	 */
	@Array({3}) 
	@Field(1) 
	public Pointer<ConSession > trade() {
		return this.io.getPointerField(this, 1);
	}
	/** internal data */
	@Field(2) 
	public int quote_overnight() {
		return this.io.getIntField(this, 2);
	}
	/** internal data */
	@Field(2) 
	public ConSessions quote_overnight(int quote_overnight) {
		this.io.setIntField(this, 2, quote_overnight);
		return this;
	}
	/** internal data */
	@Field(3) 
	public int trade_overnight() {
		return this.io.getIntField(this, 3);
	}
	/** internal data */
	@Field(3) 
	public ConSessions trade_overnight(int trade_overnight) {
		this.io.setIntField(this, 3, trade_overnight);
		return this;
	}
	/**
	 * reserved<br>
	 * C type : int[2]
	 */
	@Array({2}) 
	@Field(4) 
	public Pointer<Integer > reserved() {
		return this.io.getPointerField(this, 4);
	}
	public ConSessions() {
		super();
	}
	public ConSessions(Pointer pointer) {
		super(pointer);
	}
}
