package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:160</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ConTime extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * server's accessebility (7 days-24 hours, 0-denied, 1-allowed)<br>
	 * C type : int[7][24]
	 */
	@Array({7, 24}) 
	@Field(0) 
	public Pointer<Integer > days() {
		return this.io.getPointerField(this, 0);
	}
	/** internal variable */
	@Field(1) 
	public int dayscontrol() {
		return this.io.getIntField(this, 1);
	}
	/** internal variable */
	@Field(1) 
	public ConTime dayscontrol(int dayscontrol) {
		this.io.setIntField(this, 1, dayscontrol);
		return this;
	}
	/**
	 * reserved<br>
	 * C type : int[3]
	 */
	@Array({3}) 
	@Field(2) 
	public Pointer<Integer > reserved() {
		return this.io.getPointerField(this, 2);
	}
	public ConTime() {
		super();
	}
	public ConTime(Pointer pointer) {
		super(pointer);
	}
}
