package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.TimeT;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1249</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class DailyGroupRequest extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * group name<br>
	 * C type : char[32]
	 */
	@Array({32}) 
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/** from */
	@Field(1) 
	public TimeT from() {
		return this.io.getTimeTField(this, 1);
	}
	/** from */
	@Field(1) 
	public DailyGroupRequest from(TimeT from) {
		this.io.setTimeTField(this, 1, from);
		return this;
	}
	/** to */
	@Field(2) 
	public TimeT to() {
		return this.io.getTimeTField(this, 2);
	}
	/** to */
	@Field(2) 
	public DailyGroupRequest to(TimeT to) {
		this.io.setTimeTField(this, 2, to);
		return this;
	}
	/** total logins in request group */
	@Field(3) 
	public int total() {
		return this.io.getIntField(this, 3);
	}
	/** total logins in request group */
	@Field(3) 
	public DailyGroupRequest total(int total) {
		this.io.setIntField(this, 3, total);
		return this;
	}
	/** reserved */
	@Field(4) 
	public int reserved() {
		return this.io.getIntField(this, 4);
	}
	/** reserved */
	@Field(4) 
	public DailyGroupRequest reserved(int reserved) {
		this.io.setIntField(this, 4, reserved);
		return this;
	}
	public DailyGroupRequest() {
		super();
	}
	public DailyGroupRequest(Pointer pointer) {
		super(pointer);
	}
}
