package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1308</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ExposureValue extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * currency<br>
	 * C type : char[4]
	 */
	@Array({4}) 
	@Field(0) 
	public Pointer<Byte > currency() {
		return this.io.getPointerField(this, 0);
	}
	/** clients volume */
	@Field(1) 
	public double clients() {
		return this.io.getDoubleField(this, 1);
	}
	/** clients volume */
	@Field(1) 
	public ExposureValue clients(double clients) {
		this.io.setDoubleField(this, 1, clients);
		return this;
	}
	/** coverage volume */
	@Field(2) 
	public double coverage() {
		return this.io.getDoubleField(this, 2);
	}
	/** coverage volume */
	@Field(2) 
	public ExposureValue coverage(double coverage) {
		this.io.setDoubleField(this, 2, coverage);
		return this;
	}
	public ExposureValue() {
		super();
	}
	public ExposureValue(Pointer pointer) {
		super(pointer);
	}
}
