package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:984</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class GroupCommandInfo extends StructObject {
	static {
		BridJ.register();
	}
	/** length of users list */
	@Field(0) 
	public int len() {
		return this.io.getIntField(this, 0);
	}
	/** length of users list */
	@Field(0) 
	public GroupCommandInfo len(int len) {
		this.io.setIntField(this, 0, len);
		return this;
	}
	/** group coommand */
	@Field(1) 
	public byte command() {
		return this.io.getByteField(this, 1);
	}
	/** group coommand */
	@Field(1) 
	public GroupCommandInfo command(byte command) {
		this.io.setByteField(this, 1, command);
		return this;
	}
	/**
	 * new group<br>
	 * C type : char[16]
	 */
	@Array({16}) 
	@Field(2) 
	public Pointer<Byte > newgroup() {
		return this.io.getPointerField(this, 2);
	}
	/** new leverage */
	@Field(3) 
	public int leverage() {
		return this.io.getIntField(this, 3);
	}
	/** new leverage */
	@Field(3) 
	public GroupCommandInfo leverage(int leverage) {
		this.io.setIntField(this, 3, leverage);
		return this;
	}
	/**
	 * reserved<br>
	 * C type : int[8]
	 */
	@Array({8}) 
	@Field(4) 
	public Pointer<Integer > reserved() {
		return this.io.getPointerField(this, 4);
	}
	public GroupCommandInfo() {
		super();
	}
	public GroupCommandInfo(Pointer pointer) {
		super(pointer);
	}
}
