package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:998</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class OnlineRecord extends StructObject {
	static {
		BridJ.register();
	}
	/** connections counter */
	@Field(0) 
	public int counter() {
		return this.io.getIntField(this, 0);
	}
	/** connections counter */
	@Field(0) 
	public OnlineRecord counter(int counter) {
		this.io.setIntField(this, 0, counter);
		return this;
	}
	/** reserved */
	@Field(1) 
	public int reserved() {
		return this.io.getIntField(this, 1);
	}
	/** reserved */
	@Field(1) 
	public OnlineRecord reserved(int reserved) {
		this.io.setIntField(this, 1, reserved);
		return this;
	}
	/** user login */
	@Field(2) 
	public int login() {
		return this.io.getIntField(this, 2);
	}
	/** user login */
	@Field(2) 
	public OnlineRecord login(int login) {
		this.io.setIntField(this, 2, login);
		return this;
	}
	/** connection ip address */
	@Field(3) 
	public int ip() {
		return this.io.getIntField(this, 3);
	}
	/** connection ip address */
	@Field(3) 
	public OnlineRecord ip(int ip) {
		this.io.setIntField(this, 3, ip);
		return this;
	}
	/**
	 * user group<br>
	 * C type : char[16]
	 */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > group() {
		return this.io.getPointerField(this, 4);
	}
	public OnlineRecord() {
		super();
	}
	public OnlineRecord(Pointer pointer) {
		super(pointer);
	}
}
