package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:631</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class PluginInfo extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * plugin name<br>
	 * C type : char[128]
	 */
	@Array({128}) 
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/** plugin version */
	@Field(1) 
	public int version() {
		return this.io.getIntField(this, 1);
	}
	/** plugin version */
	@Field(1) 
	public PluginInfo version(int version) {
		this.io.setIntField(this, 1, version);
		return this;
	}
	/**
	 * plugin copyright<br>
	 * C type : char[128]
	 */
	@Array({128}) 
	@Field(2) 
	public Pointer<Byte > copyright() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * reserved<br>
	 * C type : int[32]
	 */
	@Array({32}) 
	@Field(3) 
	public Pointer<Integer > reserved() {
		return this.io.getPointerField(this, 3);
	}
	public PluginInfo() {
		super();
	}
	public PluginInfo(Pointer pointer) {
		super(pointer);
	}
}
