package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:641</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class PluginCfg extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * parameter name<br>
	 * C type : char[32]
	 */
	@Array({32}) 
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * parameter value<br>
	 * C type : char[128]
	 */
	@Array({128}) 
	@Field(1) 
	public Pointer<Byte > value() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * reserved<br>
	 * C type : int[16]
	 */
	@Array({16}) 
	@Field(2) 
	public Pointer<Integer > reserved() {
		return this.io.getPointerField(this, 2);
	}
	public PluginCfg() {
		super();
	}
	public PluginCfg(Pointer pointer) {
		super(pointer);
	}
}
