package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1176</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class RequestInfo extends StructObject {
	static {
		BridJ.register();
	}
	/** request id */
	@Field(0) 
	public int id() {
		return this.io.getIntField(this, 0);
	}
	/** request id */
	@Field(0) 
	public RequestInfo id(int id) {
		this.io.setIntField(this, 0, id);
		return this;
	}
	/** request status */
	@Field(1) 
	public byte status() {
		return this.io.getByteField(this, 1);
	}
	/** request status */
	@Field(1) 
	public RequestInfo status(byte status) {
		this.io.setByteField(this, 1, status);
		return this;
	}
	/** request time */
	@Field(2) 
	public int time() {
		return this.io.getIntField(this, 2);
	}
	/** request time */
	@Field(2) 
	public RequestInfo time(int time) {
		this.io.setIntField(this, 2, time);
		return this;
	}
	/** manager processing request (if any) */
	@Field(3) 
	public int manager() {
		return this.io.getIntField(this, 3);
	}
	/** manager processing request (if any) */
	@Field(3) 
	public RequestInfo manager(int manager) {
		this.io.setIntField(this, 3, manager);
		return this;
	}
	/** user login */
	@Field(4) 
	public int login() {
		return this.io.getIntField(this, 4);
	}
	/** user login */
	@Field(4) 
	public RequestInfo login(int login) {
		this.io.setIntField(this, 4, login);
		return this;
	}
	/**
	 * user group<br>
	 * C type : char[16]
	 */
	@Array({16}) 
	@Field(5) 
	public Pointer<Byte > group() {
		return this.io.getPointerField(this, 5);
	}
	/** user balance */
	@Field(6) 
	public double balance() {
		return this.io.getDoubleField(this, 6);
	}
	/** user balance */
	@Field(6) 
	public RequestInfo balance(double balance) {
		this.io.setDoubleField(this, 6, balance);
		return this;
	}
	/** user credit */
	@Field(7) 
	public double credit() {
		return this.io.getDoubleField(this, 7);
	}
	/** user credit */
	@Field(7) 
	public RequestInfo credit(double credit) {
		this.io.setDoubleField(this, 7, credit);
		return this;
	}
	/**
	 * bid/ask<br>
	 * C type : double[2]
	 */
	@Array({2}) 
	@Field(8) 
	public Pointer<Double > prices() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * trade transaction<br>
	 * C type : TradeTransInfo
	 */
	@Field(9) 
	public TradeTransInfo trade() {
		return this.io.getNativeObjectField(this, 9);
	}
	/**
	 * trade transaction<br>
	 * C type : TradeTransInfo
	 */
	@Field(9) 
	public RequestInfo trade(TradeTransInfo trade) {
		this.io.setNativeObjectField(this, 9, trade);
		return this;
	}
	/** gateway order volume */
	@Field(10) 
	public int gw_volume() {
		return this.io.getIntField(this, 10);
	}
	/** gateway order volume */
	@Field(10) 
	public RequestInfo gw_volume(int gw_volume) {
		this.io.setIntField(this, 10, gw_volume);
		return this;
	}
	/** gateway order ticket */
	@Field(11) 
	public int gw_order() {
		return this.io.getIntField(this, 11);
	}
	/** gateway order ticket */
	@Field(11) 
	public RequestInfo gw_order(int gw_order) {
		this.io.setIntField(this, 11, gw_order);
		return this;
	}
	/** gateway order price deviation (pips) from request price */
	@Field(12) 
	public short gw_price() {
		return this.io.getShortField(this, 12);
	}
	/** gateway order price deviation (pips) from request price */
	@Field(12) 
	public RequestInfo gw_price(short gw_price) {
		this.io.setShortField(this, 12, gw_price);
		return this;
	}
	/** C type : RequestInfo* */
	@Field(13) 
	public Pointer<RequestInfo > prev() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : RequestInfo* */
	@Field(13) 
	public RequestInfo prev(Pointer<RequestInfo > prev) {
		this.io.setPointerField(this, 13, prev);
		return this;
	}
	/**
	 * (internal use)<br>
	 * C type : RequestInfo*
	 */
	@Field(14) 
	public Pointer<RequestInfo > next() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * (internal use)<br>
	 * C type : RequestInfo*
	 */
	@Field(14) 
	public RequestInfo next(Pointer<RequestInfo > next) {
		this.io.setPointerField(this, 14, next);
		return this;
	}
	public RequestInfo() {
		super();
	}
	public RequestInfo(Pointer pointer) {
		super(pointer);
	}
}
