package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * --- server datafeed<br>
 * <i>native declaration : MT4ManagerAPI.h:813</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class ServerFeed extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * feeder file name<br>
	 * C type : char[256]
	 */
	@Array({256}) 
	@Field(0) 
	public Pointer<Byte > file() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * feeder description<br>
	 * C type : FeedDescription
	 */
	@Field(1) 
	public FeedDescription feed() {
		return this.io.getNativeObjectField(this, 1);
	}
	/**
	 * feeder description<br>
	 * C type : FeedDescription
	 */
	@Field(1) 
	public ServerFeed feed(FeedDescription feed) {
		this.io.setNativeObjectField(this, 1, feed);
		return this;
	}
	public ServerFeed() {
		super();
	}
	public ServerFeed(Pointer pointer) {
		super(pointer);
	}
}
