package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1284</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class SymbolSummary extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * symbol<br>
	 * C type : char[12]
	 */
	@Array({12}) 
	@Field(0) 
	public Pointer<Byte > symbol() {
		return this.io.getPointerField(this, 0);
	}
	/** symbol counter */
	@Field(1) 
	public int count() {
		return this.io.getIntField(this, 1);
	}
	/** symbol counter */
	@Field(1) 
	public SymbolSummary count(int count) {
		this.io.setIntField(this, 1, count);
		return this;
	}
	/** floating point digits */
	@Field(2) 
	public int digits() {
		return this.io.getIntField(this, 2);
	}
	/** floating point digits */
	@Field(2) 
	public SymbolSummary digits(int digits) {
		this.io.setIntField(this, 2, digits);
		return this;
	}
	/** symbol type (symbol group index) */
	@Field(3) 
	public int type() {
		return this.io.getIntField(this, 3);
	}
	/** symbol type (symbol group index) */
	@Field(3) 
	public SymbolSummary type(int type) {
		this.io.setIntField(this, 3, type);
		return this;
	}
	/** number of client orders */
	@Field(4) 
	public int orders() {
		return this.io.getIntField(this, 4);
	}
	/** number of client orders */
	@Field(4) 
	public SymbolSummary orders(int orders) {
		this.io.setIntField(this, 4, orders);
		return this;
	}
	/** buy volume */
	@Field(5) 
	public long buylots() {
		return this.io.getLongField(this, 5);
	}
	/** buy volume */
	@Field(5) 
	public SymbolSummary buylots(long buylots) {
		this.io.setLongField(this, 5, buylots);
		return this;
	}
	/** sell volume */
	@Field(6) 
	public long selllots() {
		return this.io.getLongField(this, 6);
	}
	/** sell volume */
	@Field(6) 
	public SymbolSummary selllots(long selllots) {
		this.io.setLongField(this, 6, selllots);
		return this;
	}
	/** average buy price */
	@Field(7) 
	public double buyprice() {
		return this.io.getDoubleField(this, 7);
	}
	/** average buy price */
	@Field(7) 
	public SymbolSummary buyprice(double buyprice) {
		this.io.setDoubleField(this, 7, buyprice);
		return this;
	}
	/** average sell price */
	@Field(8) 
	public double sellprice() {
		return this.io.getDoubleField(this, 8);
	}
	/** average sell price */
	@Field(8) 
	public SymbolSummary sellprice(double sellprice) {
		this.io.setDoubleField(this, 8, sellprice);
		return this;
	}
	/** clients profit */
	@Field(9) 
	public double profit() {
		return this.io.getDoubleField(this, 9);
	}
	/** clients profit */
	@Field(9) 
	public SymbolSummary profit(double profit) {
		this.io.setDoubleField(this, 9, profit);
		return this;
	}
	/** number of coverage orders */
	@Field(10) 
	public int covorders() {
		return this.io.getIntField(this, 10);
	}
	/** number of coverage orders */
	@Field(10) 
	public SymbolSummary covorders(int covorders) {
		this.io.setIntField(this, 10, covorders);
		return this;
	}
	/** buy volume */
	@Field(11) 
	public long covbuylots() {
		return this.io.getLongField(this, 11);
	}
	/** buy volume */
	@Field(11) 
	public SymbolSummary covbuylots(long covbuylots) {
		this.io.setLongField(this, 11, covbuylots);
		return this;
	}
	/** sell volume */
	@Field(12) 
	public long covselllots() {
		return this.io.getLongField(this, 12);
	}
	/** sell volume */
	@Field(12) 
	public SymbolSummary covselllots(long covselllots) {
		this.io.setLongField(this, 12, covselllots);
		return this;
	}
	/** average buy price */
	@Field(13) 
	public double covbuyprice() {
		return this.io.getDoubleField(this, 13);
	}
	/** average buy price */
	@Field(13) 
	public SymbolSummary covbuyprice(double covbuyprice) {
		this.io.setDoubleField(this, 13, covbuyprice);
		return this;
	}
	/** average sell price */
	@Field(14) 
	public double covsellprice() {
		return this.io.getDoubleField(this, 14);
	}
	/** average sell price */
	@Field(14) 
	public SymbolSummary covsellprice(double covsellprice) {
		this.io.setDoubleField(this, 14, covsellprice);
		return this;
	}
	/** coverage profit */
	@Field(15) 
	public double covprofit() {
		return this.io.getDoubleField(this, 15);
	}
	/** coverage profit */
	@Field(15) 
	public SymbolSummary covprofit(double covprofit) {
		this.io.setDoubleField(this, 15, covprofit);
		return this;
	}
	public SymbolSummary() {
		super();
	}
	public SymbolSummary(Pointer pointer) {
		super(pointer);
	}
}
