package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.TimeT;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1260</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class SymbolInfo extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * symbol name<br>
	 * C type : char[12]
	 */
	@Array({12}) 
	@Field(0) 
	public Pointer<Byte > symbol() {
		return this.io.getPointerField(this, 0);
	}
	/** floating point digits */
	@Field(1) 
	public int digits() {
		return this.io.getIntField(this, 1);
	}
	/** floating point digits */
	@Field(1) 
	public SymbolInfo digits(int digits) {
		this.io.setIntField(this, 1, digits);
		return this;
	}
	/** symbol counter */
	@Field(2) 
	public int count() {
		return this.io.getIntField(this, 2);
	}
	/** symbol counter */
	@Field(2) 
	public SymbolInfo count(int count) {
		this.io.setIntField(this, 2, count);
		return this;
	}
	/** visibility */
	@Field(3) 
	public int visible() {
		return this.io.getIntField(this, 3);
	}
	/** visibility */
	@Field(3) 
	public SymbolInfo visible(int visible) {
		this.io.setIntField(this, 3, visible);
		return this;
	}
	/** symbol type (symbols group index) */
	@Field(4) 
	public int type() {
		return this.io.getIntField(this, 4);
	}
	/** symbol type (symbols group index) */
	@Field(4) 
	public SymbolInfo type(int type) {
		this.io.setIntField(this, 4, type);
		return this;
	}
	/** symbol point=1/pow(10,digits) */
	@Field(5) 
	public double point() {
		return this.io.getDoubleField(this, 5);
	}
	/** symbol point=1/pow(10,digits) */
	@Field(5) 
	public SymbolInfo point(double point) {
		this.io.setDoubleField(this, 5, point);
		return this;
	}
	/** symbol spread */
	@Field(6) 
	public int spread() {
		return this.io.getIntField(this, 6);
	}
	/** symbol spread */
	@Field(6) 
	public SymbolInfo spread(int spread) {
		this.io.setIntField(this, 6, spread);
		return this;
	}
	/** spread balance */
	@Field(7) 
	public int spread_balance() {
		return this.io.getIntField(this, 7);
	}
	/** spread balance */
	@Field(7) 
	public SymbolInfo spread_balance(int spread_balance) {
		this.io.setIntField(this, 7, spread_balance);
		return this;
	}
	/** direction */
	@Field(8) 
	public int direction() {
		return this.io.getIntField(this, 8);
	}
	/** direction */
	@Field(8) 
	public SymbolInfo direction(int direction) {
		this.io.setIntField(this, 8, direction);
		return this;
	}
	/** update flag */
	@Field(9) 
	public int updateflag() {
		return this.io.getIntField(this, 9);
	}
	/** update flag */
	@Field(9) 
	public SymbolInfo updateflag(int updateflag) {
		this.io.setIntField(this, 9, updateflag);
		return this;
	}
	/** last tick time */
	@Field(10) 
	public TimeT lasttime() {
		return this.io.getTimeTField(this, 10);
	}
	/** last tick time */
	@Field(10) 
	public SymbolInfo lasttime(TimeT lasttime) {
		this.io.setTimeTField(this, 10, lasttime);
		return this;
	}
	/** bid, ask */
	@Field(11) 
	public double bid() {
		return this.io.getDoubleField(this, 11);
	}
	/** bid, ask */
	@Field(11) 
	public SymbolInfo bid(double bid) {
		this.io.setDoubleField(this, 11, bid);
		return this;
	}
	/** bid, ask */
	@Field(12) 
	public double ask() {
		return this.io.getDoubleField(this, 12);
	}
	/** bid, ask */
	@Field(12) 
	public SymbolInfo ask(double ask) {
		this.io.setDoubleField(this, 12, ask);
		return this;
	}
	/** high, low */
	@Field(13) 
	public double high() {
		return this.io.getDoubleField(this, 13);
	}
	/** high, low */
	@Field(13) 
	public SymbolInfo high(double high) {
		this.io.setDoubleField(this, 13, high);
		return this;
	}
	/** high, low */
	@Field(14) 
	public double low() {
		return this.io.getDoubleField(this, 14);
	}
	/** high, low */
	@Field(14) 
	public SymbolInfo low(double low) {
		this.io.setDoubleField(this, 14, low);
		return this;
	}
	/** commission */
	@Field(15) 
	public double commission() {
		return this.io.getDoubleField(this, 15);
	}
	/** commission */
	@Field(15) 
	public SymbolInfo commission(double commission) {
		this.io.setDoubleField(this, 15, commission);
		return this;
	}
	/** commission type */
	@Field(16) 
	public int comm_type() {
		return this.io.getIntField(this, 16);
	}
	/** commission type */
	@Field(16) 
	public SymbolInfo comm_type(int comm_type) {
		this.io.setIntField(this, 16, comm_type);
		return this;
	}
	public SymbolInfo() {
		super();
	}
	public SymbolInfo(Pointer pointer) {
		super(pointer);
	}
}
