package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.TimeT;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1345</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public class TickInfo extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * symbol<br>
	 * C type : char[12]
	 */
	@Array({12}) 
	@Field(0) 
	public Pointer<Byte > symbol() {
		return this.io.getPointerField(this, 0);
	}
	/** tick time */
	@Field(1) 
	public TimeT ctm() {
		return this.io.getTimeTField(this, 1);
	}
	/** tick time */
	@Field(1) 
	public TickInfo ctm(TimeT ctm) {
		this.io.setTimeTField(this, 1, ctm);
		return this;
	}
	/** bid */
	@Field(2) 
	public double bid() {
		return this.io.getDoubleField(this, 2);
	}
	/** bid */
	@Field(2) 
	public TickInfo bid(double bid) {
		this.io.setDoubleField(this, 2, bid);
		return this;
	}
	/** ask */
	@Field(3) 
	public double ask() {
		return this.io.getDoubleField(this, 3);
	}
	/** ask */
	@Field(3) 
	public TickInfo ask(double ask) {
		this.io.setDoubleField(this, 3, ask);
		return this;
	}
	public TickInfo() {
		super();
	}
	public TickInfo(Pointer pointer) {
		super(pointer);
	}
}
