package com.mmtap.trader.bridjapi;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.TimeT;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1095</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("MT4ManagerAPI") 
public abstract class TradeTransInfo extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : UCHAR (failed to convert type to Java (undefined type)) */
	/** flags */
	@Field(1) 
	public byte flags() {
		return this.io.getByteField(this, 1);
	}
	/** flags */
	@Field(1) 
	public TradeTransInfo flags(byte flags) {
		this.io.setByteField(this, 1, flags);
		return this;
	}
	/** trade command */
	@Field(2) 
	public short cmd() {
		return this.io.getShortField(this, 2);
	}
	/** trade command */
	@Field(2) 
	public TradeTransInfo cmd(short cmd) {
		this.io.setShortField(this, 2, cmd);
		return this;
	}
	/** order, order by */
	@Field(3) 
	public int order() {
		return this.io.getIntField(this, 3);
	}
	/** order, order by */
	@Field(3) 
	public TradeTransInfo order(int order) {
		this.io.setIntField(this, 3, order);
		return this;
	}
	/** order, order by */
	@Field(4) 
	public int orderby() {
		return this.io.getIntField(this, 4);
	}
	/** order, order by */
	@Field(4) 
	public TradeTransInfo orderby(int orderby) {
		this.io.setIntField(this, 4, orderby);
		return this;
	}
	/**
	 * trade symbol<br>
	 * C type : char[12]
	 */
	@Array({12}) 
	@Field(5) 
	public Pointer<Byte > symbol() {
		return this.io.getPointerField(this, 5);
	}
	/** trade volume */
	@Field(6) 
	public int volume() {
		return this.io.getIntField(this, 6);
	}
	/** trade volume */
	@Field(6) 
	public TradeTransInfo volume(int volume) {
		this.io.setIntField(this, 6, volume);
		return this;
	}
	/** trade price */
	@Field(7) 
	public double price() {
		return this.io.getDoubleField(this, 7);
	}
	/** trade price */
	@Field(7) 
	public TradeTransInfo price(double price) {
		this.io.setDoubleField(this, 7, price);
		return this;
	}
	/** stoploss, takeprofit */
	@Field(8) 
	public double sl() {
		return this.io.getDoubleField(this, 8);
	}
	/** stoploss, takeprofit */
	@Field(8) 
	public TradeTransInfo sl(double sl) {
		this.io.setDoubleField(this, 8, sl);
		return this;
	}
	/** stoploss, takeprofit */
	@Field(9) 
	public double tp() {
		return this.io.getDoubleField(this, 9);
	}
	/** stoploss, takeprofit */
	@Field(9) 
	public TradeTransInfo tp(double tp) {
		this.io.setDoubleField(this, 9, tp);
		return this;
	}
	/** deviation on IE */
	@Field(10) 
	public int ie_deviation() {
		return this.io.getIntField(this, 10);
	}
	/** deviation on IE */
	@Field(10) 
	public TradeTransInfo ie_deviation(int ie_deviation) {
		this.io.setIntField(this, 10, ie_deviation);
		return this;
	}
	/**
	 * comment<br>
	 * C type : char[32]
	 */
	@Array({32}) 
	@Field(11) 
	public Pointer<Byte > comment() {
		return this.io.getPointerField(this, 11);
	}
	/** pending order expiration time */
	@Field(12) 
	public TimeT expiration() {
		return this.io.getTimeTField(this, 12);
	}
	/** pending order expiration time */
	@Field(12) 
	public TradeTransInfo expiration(TimeT expiration) {
		this.io.setTimeTField(this, 12, expiration);
		return this;
	}
	/** crc */
	@Field(13) 
	public int crc() {
		return this.io.getIntField(this, 13);
	}
	/** crc */
	@Field(13) 
	public TradeTransInfo crc(int crc) {
		this.io.setIntField(this, 13, crc);
		return this;
	}
}
